# Generated by Django 4.2.21 on 2025-05-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-28 11:51:12'),
            preserve_default=False,
        ),
    ]
